export const DigestConstants = {
  LOAD_START: "LOAD_DIGEST_START",
  LOAD_SUCCESS: "LOAD_DIGEST_SUCCESS",
  LOAD_ERROR: "LOAD_DIGEST_ERROR",
  SAVE_IMAGE_URL: "SAVE_DIGEST_IMAGE_URL"
}

export const SectionConstants = {
  LOAD_START: "LOAD_SECTION_START",
  LOAD_SUCCESS: "LOAD_SECTION_SUCCESS",
  LOAD_ERROR: "LOAD_SECTION_ERROR",
  TOGGLE_VIEW: "TOGGLE_SECTION_VIEW"
}

export const UpdateConstants = {
  LOAD_START: "LOAD_UPDATE_START",
  LOAD_SUCCESS: "LOAD_UPDATE_SUCCESS",
  LOAD_ERROR: "LOAD_UPDATE_ERROR",
  SAVE_IMAGE_URL: "SAVE_UPDATE_IMAGE_URL"
}

export const CommentConstants = {
  LOAD_START: "LOAD_COMMENT_START",
  LOAD_SUCCESS: "LOAD_COMMENT_SUCCESS",
  LOAD_ERROR: "LOAD_COMMENT_ERROR"
}

